- name: Sample file for variables
  hosts: localhost
  connection: local
  vars:
    COURSE: Ansible
    TRAINER: Siva
    DURATION: 15 Hours
  tasks:
    - name: Print the variables
      debug:
        msg: "Hi, I am Learning {{ COURSE}}, Traisner is {{TRAINER}} and Durations is {{DURATION}}"
