- name: Task level variables
  hosts: localhost
  connection: local
  # vars_files:
  #   - course.yaml
  # vars:
  #   COURSE: Ansible-Play
  #   TRAINER: Siva-play
  #   DURATION: 15 Hours-play
  vars_prompt:
  - name: COURSE
    prompt: "Please enter the course name"
  - name: TRAINER
    prompt: "Please enter the trainer name"
  - name: DURATION
    prompt: "Please enter the duration of the course"
    private: yes
  tasks:
    - name: printing the task level variables
      # vars: 
      #   COURSE: Ansible
      #   TRAINER: Siva
      #   DURATION: 15 Hours
      debug:
        msg: "Hi Dudu & Bubu learning {{ COURSE}}, Trainer is {{TRAINER}} and Durations is {{DURATION}}"