- name : Course information
  hosts: local
  connection: local
  vars:
    course: "DevSecOps with AIOps"
    duration_in_hours: 150
    is_live_sessions: true
    topics:
    - Linux
    - Shell
    - Ansible
    more_details:
      months: "5"
      trainer: "Siva"
  tasks:
    - name: Display course information & Data types
      debug:
        msg: 
        - "name: {{course}}"
        - "type: {{ course | type_debug }}"

          # duration: {{ duration_in_hours }} hours
          # is_it_live: {{ is_live_sessions }}
          # topics: {{ topics }}
          # more_details: {{ more_details }}
          