- name: check given number is odd or even
  hosts: local
  connection: local
  vars_prompt:
    - name: number
      prompt: "Please enter a number"
      private: no
  tasks:
    - name: Check if the number is odd or even
      debug:
        msg: "The given number {{ number}} is even"
      when: "{{number | int % 2 == 0}}"
  
    - name: Check if the number is odd or even
      debug:
        msg: "The given number {{ number}} is odd" 
      when: "{{number | int  % 2 != 0}}"