[local]
localhost

[mongodb]
mongo.chinnimaha.online

[redis]
redis.chinnimaha.online

[mysql]
mysql.chinnimaha.online

[rabbitmq]
rabbitmq.chinnimaha.online

[catalouge]
catalouge.chinnimaha.online

[user]
user.chinnimaha.online