- name: configuring the mongo DB server
  hosts: mongodb
  become: yes
  tasks:
  - name: copy the mongodb repo
    copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    package: 
      name: mongodb-org
      state: present
  
  - name: start and enable mongodb
    service:
      name: mongodb
      state: enable