- name: Creating an ec2 instance for roboshop application
  hosts: local
  connection: local
  vars:
    instance_type: t3.micro
    instances: ["mongo", "redis", "mysql", "rabbitmq", "catalouge", "user", "cart", "shipping", "payment", "frontend"]
    image_id: ami-0220d79f3f480ecf5
    domain_name: chinnimaha.online
    action: create
  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "roboshop-{{ item }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        region: us-east-1
        security_groups: 
          - "roboshop-{{ item }}"
      loop: "{{ instances }}"
      register: ec2_instance
      when: action == "create"

    - name: print ec2 instance details
      debug:
        msg: "{{ ec2_instance }}"

    - name: print the private ip address of the instances
      debug:
        msg: 
        - "Instance name:{{ item.instances[0].tags.Name }}"
        - "Instance_name:{{ item.item }}"
        - "Private IP address: {{ item.instances[0].private_ip_address }}"
      loop: "{{ ec2_instance.results }}"
  
